username = input('введите ваше имя: ')
title = input('введите заголовок: ')
content = input('введите заметку: ')
status = input('введите статус заметки: ')
from note_manager.data_changer import created_date, issue_date, temp_created_date, temp_issue_date
print(username)
print(title)
print(content)
print(status)
print(temp_created_date)
print(temp_issue_date)
